name: Map_wall
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - cartopy
  - numpy
  - scipy
  - pandas
  - metpy
  - cfgrib
  - beautifulsoup4
  - fsspec
  - arm_pyart
  - xradar
  - xarray-datatree
  - synopticpy
  - goes2go
  - pip
  - pip:
    - "matplotlib<3.10"
    - herbie-data
    - sounderpy
    - "s3fs==2026.7.0"