name: Map_wall
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - matplotlib
  - cartopy
  - numpy
  - scipy
  - pandas
  - metpy
  - cfgrib
  - fsspec
  - s3fs
  - arm_pyart
  - pip
  - pip:
    - herbie-data
    - sounderpy